/productRequest:
  get:
    tags:
      - productRequest
    description: >-
      Returns all the product requests. You can filter, sort ,limit number of
      results, paginate and limit the returned fields. For filter, you need to
      use the fields's name and value. You can filter using some operators.
      They are gte, gt ,lte, lt, regex.
    parameters:
      - in: query
        name: sort
        description: >-
          name of the field to sort
        required: false
        type: string
      - in: query
        name: limit
        description: "number of elements to return, default is 1000"
        required: false
        type: number
      - in: query
        name: page
        description: "page number for the results, default is 1"
        required: false
        type: number
      - in: query
        name: fields
        description: >-
          Fields you want in the returned elements.
        required: false
        type: number
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              $ref: "../components/responses/_index.yaml#/ProductRequestList"
      "400":
        description: Invalid body
"/productRequest/{id}":
  get:
    tags:
      - productRequest
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              $ref: "../components/responses/_index.yaml#/ProductRequest"
      "400":
        description: Invalid
  patch:
    tags:
      - productRequest
    parameters:
      - in: body
        name: body
        schema:
          $ref: "../components/schemas/_index.yaml#/ProductRequest"
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              $ref: "../components/responses/_index.yaml#/ProductRequest"
      "400":
        description: Invalid
  delete:
    tags:
      - productRequest
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              $ref: "../components/responses/_index.yaml#/NullData"
      "400":
        description: Invalid
"/productRequest/{mpid}/vendor/{vid}":
