# Generated by Django 3.0.6 on 2020-05-20 13:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_left', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.CharField(max_length=200)),
                ('is_free_shipment', models.BooleanField()),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo_company', models.CharField(choices=[('aras', 'Aras Kargo'), ('mng', 'MNG Kargo'), ('yurtici', 'Yurtici Kargo'), ('ptt', 'PTT Kargo'), ('ups', 'UPS'), ('other', 'Other')], default='other', max_length=10)),
            ],
        ),
    ]
