# Generated by Django 3.0.6 on 2020-05-27 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('amount_left', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.CharField(max_length=200)),
                ('is_free_shipment', models.BooleanField()),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo_company', models.CharField(choices=[('aras', 'Aras Kargo'), ('mng', 'MNG Kargo'), ('yurtici', 'Yurtici Kargo'), ('ptt', 'PTT Kargo'), ('ups', 'UPS'), ('other', 'Other')], default='other', max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_calculator.Vendor')),
            ],
        ),
    ]
