# Generated by Django 3.0.6 on 2020-05-20 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lon',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
    ]
