# Generated by Django 3.0.6 on 2020-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lon',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
