# Generated by Django 3.0.6 on 2020-05-26 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Customer')),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ordered_products',
            field=models.ManyToManyField(through='recommend.Purchase', to='recommend.Product'),
        ),
        migrations.CreateModel(
            name='WillBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('customer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer1', to='recommend.Customer')),
                ('customer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer2', to='recommend.Customer')),
            ],
            options={
                'unique_together': {('customer1', 'customer2')},
            },
        ),
    ]
