# Generated by Django 3.0.6 on 2020-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_remove_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ordered_products',
            field=models.ManyToManyField(blank=True, through='recommend.Purchase', to='recommend.Product'),
        ),
    ]
