---
- hosts: apps
  become: yes

  vars:
    - homeDir: /home/ubuntu
    - appDir : backend-app
    - owner: bounswe
    - projectName: bounswe2020group8
    - nodeVersion: '12'

  tasks:
  - name: Check if nodejs is installed
    shell: node -v
    register: isNode
    ignore_errors: yes

  - name: Install node if not installed
    shell: |
      apt-get update
      curl -sL https://deb.nodesource.com/setup_{{nodeVersion}}.x | sudo -E bash -
      sudo apt-get install -y nodejs
      node -v
    when: isNode.rc != 0
  
  - name: Install Packages
    apt: 
      name: git
      update_cache: yes

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Create APP Directory
    file: 
      path: "{{homeDir}}/{{appDir}}"
      owner: ubuntu
      state: directory
    become: no

  - name: Check for Project directory
    stat:
      path: "{{homeDir}}/{{appDir}}/{{projectName}}"
    register: file_details
    become: no

  - name: Clone the Repo if the repo is not cloned yet
    shell: |
      git clone https://github.com/{{owner}}/{{projectName}}.git
      cd {{projectName}}
      git fetch origin 
      git checkout backend
    args:
      chdir: "{{homeDir}}/{{appDir}}"
    when: file_details.stat.exists == false 
    ignore_errors: yes
    become: no

  - name: Get the new version of the app
    shell: |
      git reset --hard
      git pull origin
    args:
      chdir: "{{homeDir}}/{{appDir}}/{{projectName}}"
    when: file_details.stat.exists 
    ignore_errors: yes
    become: no


  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/{{projectName}}/backend
    register: npm_finished
    become: no


  - name: Stop backend-app
    command: pm2 stop backend-app chdir={{homeDir}}/{{appDir}}/{{projectName}}/backend
    when:  file_details.stat.exists 
    ignore_errors: yes
    become: no

  - name: Start backend-app
    command: pm2 start server.js --name backend-app chdir={{homeDir}}/{{appDir}}/{{projectName}}/backend
    ignore_errors: yes
    when: npm_finished is succeeded and file_details.stat.exists 
    become: no
