ProductRequestList:
  allOf:
    - $ref: "./general.yaml#/ApiResponse"
    - type: object
      properties:
        results:
          type: number
        data:
          type: array
          items:
            $ref: "../schemas/_index.yaml#/ProductRequest"
ProductRequest:
  allOf:
    - $ref: "./general.yaml#/ApiResponse"
    - type: object
      properties:
        data:
          $ref: "../schemas/_index.yaml#/ProductRequest"
