name: Web-autodeploy-dev
on:
  workflow_dispatch:
  push:
    branches:
      - web
    paths:
      - 'web/**'
      - '.github/web-deployment/dev-hosts'


jobs:
  build:
    env:
      IMAGE_NAME: carouselapp/carousel-frontend
      DOCKER_USERNAME: carouselapp
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps: 

      - name: Check Ansible Playbook
        run: |
          ansible-playbook --version
      
      - name: Checkout to web branch
        uses: actions/checkout@v2
        with:
          path: frontend
          ref: web


      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PROD_BACKEND_KEY }}
          name: id_rsa
          known_hosts: " "


      - name: Build and push the image
        working-directory: frontend/web/carousel
        run: |
          docker build . -t ${IMAGE_NAME}
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push ${IMAGE_NAME}
          

      - name: Checkout to backend branch
        uses: actions/checkout@v2
        with:
          path: backend
          ref: backend


      - name: Run Ansible Playbook
        working-directory: ./backend/.github/web-deployment
        run: |
          HOSTS=$( grep -oh -E "^([[:digit:]]+\.){3}[[:digit:]]+" dev-hosts)
          ssh-keyscan $HOSTS >> ~/.ssh/known_hosts
          ansible-playbook web-dev.yml -i dev-hosts

          